In [38]:
#data manipulation libraries

import pandas as pd
#data manipulation libraries
import csv
import pandas as pd
import numpy as np
import re
import string

#methods and stopwords
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

##Machine Learning Libraries
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


import warnings
warnings.filterwarnings ("ignore")

In [26]:
pip install --user -U nltk

Note: you may need to restart the kernel to use updated packages.


In [3]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hchas\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [42]:
df = pd.read_csv(r"D:\Coursera\engtweets.csv")

In [43]:
dataset =df[['Sentiment','text']]
text, sentiment = list(dataset['text']), list(dataset['Sentiment'])

In [44]:
def preprocess(textdata):
    processedText = []
    
    # Create Lemmatizer and Stemmer.
    wordLemm = WordNetLemmatizer()
    
    # Defining regex patterns.
    urlPattern        = r"((http://)[^ ]*|(https://)[^ ]*|( www\.)[^ ]*)"
    userPattern       = '@[^\s]+'
    alphaPattern      = "[^a-zA-Z0-9]"
    sequencePattern   = r"(.)\1\1+"
    seqReplacePattern = r"\1\1"
    
    for tweet in textdata:
        tweet = tweet.lower()
        
        # Replace all URls with 'URL'
        tweet = re.sub(urlPattern,' URL',tweet)
        
           
        # Replace @USERNAME to 'USER'.
        tweet = re.sub(userPattern,' USER', tweet)        
        # Replace all non alphabets.
        tweet = re.sub(alphaPattern, " ", tweet)
        # Replace 3 or more consecutive letters by 2 letter.
        tweet = re.sub(sequencePattern, seqReplacePattern, tweet)

        tweetwords = ''
        for word in tweet.split():
            # Checking if the word is a stopword.
            #if word not in stopwordlist:
            if len(word)>1:
                # Lemmatizing the word.
                word = wordLemm.lemmatize(word)
                tweetwords += (word+' ')
            
        processedText.append(tweetwords)
        
    return processedText

In [45]:
X_train, X_test, y_train, y_test = train_test_split(text, sentiment,
                                                    test_size = 0.25, random_state = 0) #splitting the data into training and test set
print(f'Data Split done.')

Data Split done.


In [9]:
import time
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hchas\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [28]:

nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\hchas\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\omw-1.4.zip.


True

In [29]:

nltk.download('wordnet')
t = time.time()
processedtext = preprocess(text)
print(f'Text Preprocessing complete.')


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hchas\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Text Preprocessing complete.


In [46]:
vectoriser = CountVectorizer(ngram_range=(1,2), max_features=500000)
vectoriser.fit(X_train)
print(f'Vectoriser fitted.')
print('No. of feature_words: ', len(vectoriser.get_feature_names()))

Vectoriser fitted.
No. of feature_words:  311301


In [47]:
X_train = vectoriser.transform(X_train)
X_test  = vectoriser.transform(X_test)
print(f'Data Transformed.')

Data Transformed.


In [49]:
import sklearn.metrics as metrics

In [50]:
LRmodel = LogisticRegression(C = 2, max_iter = 1000, n_jobs=-1)
LRmodel.fit(X_train, y_train)
ys_predict = LRmodel.predict(X_test)
#Display the outcome of classification
print('Classification Report: \n',metrics.classification_report(y_test, ys_predict))
print('Confusion Matrix: \n',metrics.confusion_matrix(y_test, ys_predict))
print('Accuracy Score: \n',metrics.accuracy_score(y_test, ys_predict))

Classification Report: 
               precision    recall  f1-score   support

    Negative       0.86      0.84      0.85      2819
     Neutral       0.74      0.86      0.80      2001
    Positive       0.87      0.76      0.81      2116

    accuracy                           0.82      6936
   macro avg       0.82      0.82      0.82      6936
weighted avg       0.83      0.82      0.82      6936

Confusion Matrix: 
 [[2357  310  152]
 [ 178 1727   96]
 [ 208  291 1617]]
Accuracy Score: 
 0.8219434832756632


In [51]:
NB=MultinomialNB(alpha=1)
NB.fit(X_train,y_train)
ys_predict=NB.predict(X_test)
print('Classification Report: \n',metrics.classification_report(y_test, ys_predict))
print('Confusion Matrix: \n',metrics.confusion_matrix(y_test, ys_predict))
print('Accuracy Score: \n',metrics.accuracy_score(y_test, ys_predict))

Classification Report: 
               precision    recall  f1-score   support

    Negative       0.60      0.94      0.73      2819
     Neutral       0.87      0.36      0.51      2001
    Positive       0.75      0.59      0.66      2116

    accuracy                           0.67      6936
   macro avg       0.74      0.63      0.63      6936
weighted avg       0.72      0.67      0.64      6936

Confusion Matrix: 
 [[2661   52  106]
 [ 973  714  314]
 [ 819   52 1245]]
Accuracy Score: 
 0.6660899653979239


In [36]:
SVCmodel = LinearSVC()
SVCmodel.fit(X_train, y_train)
ys_predict = SVCmodel.predict(X_test)
#Display the outcome of classification
print('Classification Report: \n',metrics.classification_report(y_test, ys_predict))
print('Confusion Matrix: \n',metrics.confusion_matrix(y_test, ys_predict))
print('Accuracy Score: \n',metrics.accuracy_score(y_test, ys_predict))

Classification Report: 
               precision    recall  f1-score   support

    Negative       0.90      0.87      0.89       555
     Neutral       0.80      0.90      0.84       412
    Positive       0.88      0.81      0.85       421

    accuracy                           0.86      1388
   macro avg       0.86      0.86      0.86      1388
weighted avg       0.86      0.86      0.86      1388

Confusion Matrix: 
 [[482  47  26]
 [ 21 370  21]
 [ 30  48 343]]
Accuracy Score: 
 0.8609510086455331


In [52]:
DTCModel = DecisionTreeClassifier(random_state=0)
DTCModel.fit(X_train, y_train)
ys_predict = DTCModel.predict(X_test)
#Display the outcome of classification
print('Classification Report: \n',metrics.classification_report(y_test, ys_predict))
print('Confusion Matrix: \n',metrics.confusion_matrix(y_test, ys_predict))
print('Accuracy Score: \n',metrics.accuracy_score(y_test, ys_predict))

Classification Report: 
               precision    recall  f1-score   support

    Negative       0.75      0.71      0.73      2819
     Neutral       0.66      0.77      0.71      2001
    Positive       0.72      0.66      0.69      2116

    accuracy                           0.71      6936
   macro avg       0.71      0.71      0.71      6936
weighted avg       0.72      0.71      0.71      6936

Confusion Matrix: 
 [[2008  449  362]
 [ 288 1531  182]
 [ 364  348 1404]]
Accuracy Score: 
 0.7126585928489043


In [54]:
RFCModel = RandomForestClassifier(n_estimators=100)
RFCModel.fit(X_train, y_train)
ys_predict = RFCModel.predict(X_test)
#Display the outcome of classification
print('Classification Report: \n',metrics.classification_report(y_test, ys_predict))
print('Confusion Matrix: \n',metrics.confusion_matrix(y_test, ys_predict))
print('Accuracy Score: \n',metrics.accuracy_score(y_test, ys_predict))

Classification Report: 
               precision    recall  f1-score   support

    Negative       0.74      0.81      0.77      2819
     Neutral       0.66      0.82      0.73      2001
    Positive       0.88      0.56      0.68      2116

    accuracy                           0.74      6936
   macro avg       0.76      0.73      0.73      6936
weighted avg       0.76      0.74      0.73      6936

Confusion Matrix: 
 [[2283  431  105]
 [ 295 1645   61]
 [ 513  427 1176]]
Accuracy Score: 
 0.7358708189158016
